name: uv10
favicon: null
layout_spectrum: 0.94853
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00A880'
    - '#000000'
    - '#30A8E0'
    - '#68B8E0'
  brandStrength: 0.138513
  lightness: 0.319256
  saturation: 0.501689
  rhythmicContrast: 0.491554
purpose:
  - name: null
    item: null
    url: null
