analytics: {}
color:
  brandColors:
    - '#000000'
    - '#00A880'
    - '#000000'
    - '#30A8E0'
    - '#68B8E0'
  brandStrength: 0.138513
  lightness: 0.319256
  rhythmicContrast: 0.491554
  saturation: 0.501689
cta: {}
layout_spectrum: 0.261824
name: uv10
opengraph: {}
purpose:
  - {}
typography_spectrum: 1
