name: uv10
favicon: null
layout_spectrum: 0.50989
typography_spectrum: 0.815878
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00A880'
    - '#000000'
    - '#30A8E0'
    - '#68B8E0'
  brandStrength: 0.694522
  lightness: 0.588422
  saturation: 0.6875
  rhythmicContrast: 0.072681
purpose:
  - name: null
    item: null
    url: null
