name: uv10
favicon: null
layout_spectrum: 0.65661
typography_spectrum: 1
title: uv10 Investments
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00A880'
    - '#000000'
    - '#30A8E0'
    - '#68B8E0'
  brandStrength: 0.3125
  lightness: 0.1875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
