analytics: {}
color:
  brandColors:
    - '#B0B8A8'
    - '#214264'
    - '#487088'
    - '#70A0D0'
    - '#A0C0D8'
  brandStrength: 0.287162
  lightness: 0.319256
  rhythmicContrast: 0.491554
  saturation: 0.256756
cta: {}
layout_spectrum: 0.261824
name: uv10
opengraph: {}
purpose:
  - {}
typography_spectrum: 1
