analytics: {}
color:
  brandColors:
    - '#000000'
    - '#7A4B0B'
    - '#68A8A0'
    - '#F0B058'
    - '#90D0E0'
  brandStrength: 0.5
  lightness: 0.506756
  rhythmicContrast: 0.491554
  saturation: 0.8125
cta: {}
layout_spectrum: 0.261824
name: uv10
opengraph: {}
purpose:
  - {}
typography_spectrum: 1
